

FOLLOW_GOOGLE_LINKS: False
allImages: False

type: "western"

baseUrl: [
	"https://www.fictionpress.com/",
	"http://www.fictionpress.com/",
	]

trigger: False

badwords: [
			"/about/",
			"/join-us/",
			"/chat/",
			'&format=pdf',
			'?format=pdf',
			'?replytocom=',
			"/forum/",
			"/forum",
			"/forums/",
			"/forums",
			"/games/",
			"/betareaders/",
			"/poetry/", # Really?

			"/post.php?",
			"/author.php?",
			"fictionpress.com/atom/u/",
			]

# Content Stripping needs to be determined.
decomposeBefore: [

]

decompose: [
	{'id' : "top"},
	{'id' : "p_footer"},
	{'id' : "profile_top"},
	{'id' : "review"},
	{'class' : "zmenu"},
	{'class' : "lc-wrapper"},
]

stripTitle: []


destyle : [
	["div",  {}],
	["span", {}],
]


preserveAttrs : [
	["button", 'id'],
	["button", 'onclick'],
	["button", 'type'],
	["button", 'btn'],
	["select", ''],
]

